# Generated by Django 5.0.4 on 2024-04-18 12:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_Activated', models.BooleanField(default=False)),
            ],
        ),
    ]
